# Generated by Django 5.2.6 on 2025-09-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_player_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
