# Generated by Django 5.2.6 on 2025-09-23 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_gamesession_current_player_order_player_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='current_player_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
