# Generated by Django 5.2.6 on 2025-09-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_gamesession_current_player_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True),
        ),
    ]
