# Generated by Django 5.0.14 on 2025-09-24 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gamesession_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
