# Generated by Django 5.0.14 on 2025-09-25 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gamesession_modified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_words', to='home.gamesession')),
            ],
            options={
                'unique_together': {('game_session', 'word')},
            },
        ),
    ]
